server:
  port: 9600
  servlet:
    context-path: /want-etl-center
  compression:
    enabled: true
spring:
  application:
    name: want-etl-center
  servlet:
    multipart:
      location: ${user.home}
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: '@spring.profiles.active@'
  jackson:
    default-property-inclusion: non-null
swagger:
  basePackage: com.want
---
debug: true
spring:
  profiles: dev
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.231.8.147:3306/wantETL?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
      username: wantetl
      password: P@ssw0rd
      pool-name: HikariPool-custom
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 600000
      validation-timeout: 5000
      connection-test-query: SELECT 1
ldap:
  url: ldap://ldst.want-want.com:5389
  userDn: CN=ron,CN=Partition1,DC=want-moss,DC=com
  password: 123456
  base: CN=Users,CN=Partition1,DC=want-moss,DC=com
  
---
debug: true
spring:
  profiles: prd
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.231.8.147:3306/wantETL?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
      username: wantetl
      password: P@ssw0rd
      pool-name: HikariPool-custom
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 600000
      validation-timeout: 5000
      connection-test-query: SELECT 1
ldap:
  url: ldap://ldsp.want-want.com:389
  userDn: CN=admin,CN=Users,CN=PartitionWWLDS1,DC=want-want,DC=com
  password: iWantWant0316
  base: CN=Users,CN=PartitionWWLDS1,DC=want-want,DC=com